keys:
  - &vaultwarden age1l7hymts6l90zccyqry8rcz7jgzpkl00xsxxsegntzflwscwlwdxsl72jdr
  - &dev age1sur65t9wa9s0krds32kx9h379masmkyf663wwwav2ye0v5syyv2qkaxsd8
  - &desktop age1j7rx2tpjsltwtpvdfyaaq3pflzx37cd9neycgsujt2hpuuvsva4sjupjjp

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *vaultwarden
          - *dev
          - *desktop